{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpg-database.fullname" . }}-admin
  labels: {{- include "cnpg-database.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  data:
    - remoteRef:
        key: {{ required "externalSecrets.admin.remoteKey is required" .Values.externalSecrets.admin.remoteKey }}
      secretKey: password
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef: {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "cnpg-database.fullname" . }}-admin
    template:
      {{- with .Values.externalSecrets.secret.metadata }}
      metadata: {{- toYaml . | nindent 8 }}
      {{- end }}
      data:
        password: '{{ `{{ .password }}` }}'
        username: {{ .Values.externalSecrets.admin.username }}
      type: kubernetes.io/basic-auth
{{- end }}
