{{- if and .Values.externalSecrets.enabled .Values.backup.enabled (not .Values.backup.objectStore.credentials.secretName) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpg-database.backupSecret" . }}
  labels: {{- include "cnpg-database.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.externalSecrets.backup.accessKeyRemoteKey }}
      secretKey: {{ .Values.backup.objectStore.credentials.accessKeyKey }}
    - remoteRef:
        key: {{ .Values.externalSecrets.backup.secretKeyRemoteKey }}
      secretKey: {{ .Values.backup.objectStore.credentials.secretKeyKey }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef: {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "cnpg-database.backupSecret" . }}
{{- end }}
