{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpg-database.fullname" . }}-user
  labels: {{- include "cnpg-database.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  data:
    - remoteRef:
        key: {{ required "externalSecrets.user.remoteKey is required" .Values.externalSecrets.user.remoteKey }}
      secretKey: password
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef: {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "cnpg-database.fullname" . }}-user
    template:
      data:
        password: '{{ `{{ .password }}` }}'
        username: {{ default (include "cnpg-database.owner" .) .Values.externalSecrets.user.username }}
      type: kubernetes.io/basic-auth
{{- end }}
