{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cnpg-database.fullname" . }}-backups
  labels: {{- include "cnpg-database.labels" . | nindent 4 }}
spec:
{{- tpl (.Files.Get "files/alerts.yaml") . | nindent 2 }}
{{- end }}
